CODE_URL = 'https://www.code.go.kr/etc/codeFullDown.do'
CODE_COOKIES = {
    'SCOUTER': 'z10isuk0tsd7ug',
    'JSESSIONID': 'v3Gd4M0hEtndkwRFcLNtPVpK.CODROOTserver1',
    'clientid': '070090329080',
    'GPKISecureWebSession': 'LWdvSmpiUIDnJ63DR92H',
}
CODE_HEADERS = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'ko,en-US;q=0.9,en;q=0.8,ko-KR;q=0.7',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Length': '221',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Host': 'www.code.go.kr',
    'Origin': 'https://www.code.go.kr',
    'Referer': 'https://www.code.go.kr/stdcode/regCodeL.do',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"macOS"',
    'Sec-Fetch-Dest': 'iframe',
    'Sec-Fetch-Mode': 'navigate',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-User': '?1',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36',
}
CODE_DATA = {
    'cPage': '1',
    'regionCd_pk': '',
    'chkWantCnt': '0',
    'reqSggCd': '',
    'reqUmdCd': '',
    'reqRiCd': '',
    'searchOk': '',
    'codeseId': '법정동코드',
    'pageSize': '10',
    'regionCd': '',
    'locataddNm': '',
    'sidoCd': '*',
    'sggCd': '*',
    'umdCd': '*',
    'riCd': '*',
    'disuseAt': '0',
    'stdate': '',
    'enddate': '',
}