INIT_DIRECTORY = "./data/"
REGION_CODE_DIRECTORY = "./data/Region_Code/"
REGION_CODE_SUB_DIRECTORY = "./data/Region_Code/addr_code/"
CSV_DIRECTORY = "./data/csv/"
CSV_ADD_DIRECTORY = "./data/csv/additional/"
XLS_DIRECTORY = "./data/xls/"
TX_DIRECTORY = "./data/tx/"
ACTUAL_TX_DIRECTORY = "./data/tx/actual_tx/"
ACTUAL_TX_DIRECTORY_CSV = "./data/tx/actual_tx/csv/"
CHARTERED_RENT_DIRECTORY = "./data/tx/chartered_rent/"
CHARTERED_RENT_DIRECTORY_CSV = "./data/tx/chartered_rent/csv/"
AC_CH_FINAL_DIRECTORY = "./data/tx/final_files/"

