ACTUAL_TX_URL = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?"
ACTUAL_TX_SERVICE_KEY = "QpzNJfls7pUGoTMgVF5CjC8i9Gw5jqbV4rpZdLHMqmpUlfOh7gpKvDNTYILSlkfvZZKpSh6NWDIhMRLQmxwA4A%3D%3D"

CHARTERED_RENT_URL = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptRent?"
CHARTERED_RENT_KEY = "QpzNJfls7pUGoTMgVF5CjC8i9Gw5jqbV4rpZdLHMqmpUlfOh7gpKvDNTYILSlkfvZZKpSh6NWDIhMRLQmxwA4A%3D%3D"

GREEN_SERVICE_KEY = "QpzNJfls7pUGoTMgVF5CjC8i9Gw5jqbV4rpZdLHMqmpUlfOh7gpKvDNTYILSlkfvZZKpSh6NWDIhMRLQmxwA4A%3D%3D"
DORUMUGS_SERVICE_KEY = "S8O%2B%2FfTUa2CRXrJsczyX%2BywDuL64E9pIP%2FCB%2FH%2BPUfTKxc2l1tVdCjzSHqlzMk5JzuUbjFx6%2F5pm21L4MFdDpQ%3D%3D"
BLACK_SERVICE_KEY = "yXRG8TbNgrlYcJjFSLoCb4AZJeu5Gh1%2BReP9ezNcJ5giBLVAPBAekEyQgG2sU8unGjNwONhKSxvNDtatCyFpVQ%3D%3D"